
# 地形
(TILE_EMPTY, TILE_BRICK, TILE_STEEL, TILE_WATER, TILE_GRASS, TILE_FROZE) = range(6)
# 玩家
TANK_PLAYER1 = 51
TANK_PLAYER2 = 52
TANK_PLAYER3 = 53
# 子弹
TANK_BULLET = 61
# 方向
(DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LEFT) = range(4)
# 坦克状态
(STATE_SPAWNING, STATE_DEAD, STATE_ALIVE, STATE_EXPLODING) = range(4)
